[package]
name = "buttplug"
version = "0.2.3"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[features]
default=["client", "server", "serialize_json", "btleplug-manager", "client-ws-ssl", "xinput", "serial-manager"]
client=[]
server=[]
serialize_json=[]
xinput=[]
btleplug-manager=["btleplug"]
serial-manager=["serialport"]
client-ws=["client", "serialize_json", "ws"]
client-ws-ssl=["client", "serialize_json", "ws", "ws/ssl", "openssl"]

[dependencies]
log = "0.4.8"
# buttplug_derive = { path = "../buttplug_derive" }
buttplug_derive = "0.2.0"
futures = "0.3.4"
futures-util = "0.3.4"
async-std = { version = "1.5.0", features = ["unstable"] }
async-trait = "0.1.30"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
serde_repr = "0.1.5"
uuid = { version = "0.8.1", features = ["serde"] }
ws = { version = "0.9.1", features = ["ssl"], optional = true }
openssl = { version = "0.10.29", optional = true }
url = "2.1.1"
btleplug = { version = "0.4.2", optional = true }
# btleplug = { path = "../../btleplug", optional = true}
# btleplug = { git = 'https://github.com/deviceplug/btleplug', branch = 'master', optional = true }
strum_macros = "0.18.0"
strum = "0.18.0"
once_cell = "1.3.1"
paste = "0.1.10"
broadcaster = { version = "1.0.0", features = ["default-channels"] }
futures-channel = "0.3.4"
lazy_static = "1.4.0"
byteorder = "1.3.4"
valico = "3.2.0"
serialport = { version = "3.3.0", optional = true }

[target.'cfg(windows)'.dependencies]
rusty-xinput = "1.2.0"

[dev-dependencies]
env_logger = "0.7.1"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true

# Only build docs on one platform (linux)
[package.metadata.docs.rs]
targets = []
